### ISSUE TITLE
an error LookupError: App 'custom_user' doesn't have a 'User' model.

### ISSUE THREAD

**Issue by art3mHQ** [jmfederico/django-use-email-as-username#4]
* Django use Email as Username version: current
* Django version: 3.0
* Python version: 3.7
* Operating System: macos

### Description

When follow the readme instructions i received an error when  makemigration 

if we make a link to model (AUTH_USER_MODEL = 'YOUR_APP.User') but we didn't create User model inside, how it supposed to work? Or i'm wrong? 

thanks!

### What I Did

```
$ python manage.py makemigrations
Traceback (most recent call last):
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/apps/config.py", line 178, in get_model
    return self.models[model_name.lower()]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 156, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/apps/registry.py", line 210, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/apps/config.py", line 181, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'custom_user' doesn't have a 'User' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/contrib/auth/admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/contrib/auth/forms.py", line 20, in <module>
    UserModel = get_user_model()
  File "/Users/art3m/python/django3/floo_env/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 161, in get_user_model
    "AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'custom_user.User' that has not been installed

```

**Comment by jmfederico** [comment]
There was a compatibility issue with Django 3. Fix has been implemented on master branch.

Can you please test against the master branch?
`pip install git+https://github.com/jmfederico/django-use-email-as-username.git`

Can you provide your `settings.py` and confirm if a module was successfully created with the command `python manage.py create_custom_user_app`?
